### ISSUE TITLE
train.py throws ValueError

### ISSUE THREAD

**Issue by malyasova** [DongyaoZhu/VQ-VAE-WaveNet#2]
I run:
python train.py VCTK
I get:
44242it [01:17, 574.28it/s]
data total: 44242
input x: (?, 6144, 1)
input h: (?, 1, 109)
dr_1: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_2: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_4: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_8: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_16: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_32: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_64: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_128: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_256: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_512: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_1: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_2: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_4: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_8: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_16: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_32: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_64: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_128: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_256: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_512: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_1: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_2: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_4: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_8: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_16: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_32: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_64: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_128: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_256: d: (?, 6144, 128)   en: (?, 6144, 128)
dr_512: d: (?, 6144, 128)   en: (?, 6144, 128)
en: (?, 24, 64)
z_e: (?, 24, 64)
embedding: (512, 512)
Traceback (most recent call last):
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 64 and 512 for 'embedding/sub' (op: 'Sub') with input shapes: [?,24,1,64], [512,512].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 85, in <module>
    model.build(learning_rate_schedule=learning_rate_schedule)
  File "/home/robot/hdd2/Vikas_stuff/VQ-VAE-WaveNet/model.py", line 113, in build
    self._build()
  File "/home/robot/hdd2/Vikas_stuff/VQ-VAE-WaveNet/model.py", line 110, in _build
    self._discretise()
  File "/home/robot/hdd2/Vikas_stuff/VQ-VAE-WaveNet/model.py", line 39, in _discretise
    distances = tf.reduce_sum((expanded_ze - self.embedding) ** 2, axis=-1)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 897, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10855, in sub
    "Sub", x=x, y=y, name=name)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2027, in __init__
    control_input_ops)
  File "/home/robot/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 64 and 512 for 'embedding/sub' (op: 'Sub') with input shapes: [?,24,1,64], [512,512].

**Comment by DongyaoZhu** [comment]
Hi,
That's a hard-coded latent dimension mismatching with what's in model_parameters.json, which I fixed now.

**Comment by malyasova** [comment]
That's what I suspected, thank you!
